### ISSUE TITLE
Update firebase-core and google-services dependencies on gradle

### ISSUE THREAD

**Issue by GustavoContreiras** [mdanics/fluttergram#48]
My android/build.gradle:
```
dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        //classpath 'com.google.gms:google-services:3.2.0' //fluttergram original
        classpath 'com.google.gms:google-services:4.0.1' //firebase tutorial recommended
}
```

My app/build.gradle:
```
dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    //compile 'com.google.firebase:firebase-core:11.8.0' //fluttergram original
    implementation 'com.google.firebase:firebase-core:16.0.1' //firebase tutorial recommended
}
```

My pubspec.yaml:
```
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.2+1
  circular_profile_avatar: ^0.1.6
  image_picker: 0.4.1
  firebase_storage: 1.0.4
  # firebase_auth: 0.6.2+1
  firebase_auth: 0.7.0
  google_sign_in: ^3.2.1
  uuid: 1.0.3
  image: 2.0.4
  path_provider: 0.4.1
  font_awesome_flutter: 8.0.1
  async: "^2.0.4"
  http: "^0.12.0"
  shared_preferences: "^0.4.1"
  cached_network_image: "^0.5.0"
  firebase_messaging: ^2.0.2
  location: ^1.4.1
  geocoder: ^0.1.1
```

I think it's ok to update it. Working without errors here (in the version without AndroidX).
